apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-pipeline: cnapp-common
spec:
  securityContext:
    runAsUser: 0
  containers:
    - command:
        - cat
      image: "docker-registry.colortokens.com/cnapp/docker-sbt:18.06-1.3.13"
      #image: "mozilla/sbt"
      imagePullPolicy: IfNotPresent
      name: docker-sbt
      tty: true
      volumeMounts:
        -
          name: dockersock
          mountPath: "/var/run/docker.sock"
          readOnly: true
    - command:
        - cat
      image: "docker:18.06"
      imagePullPolicy: IfNotPresent
      name: docker
      tty: true
      volumeMounts:
        -
          name: dockersock
          mountPath: "/var/run/docker.sock"
          readOnly: true
    -
      command:
        - cat
      image: "gittools/gitversion:5.0.1-linux"
      imagePullPolicy: IfNotPresent
      name: gitversion
      tty: true
  imagePullSecrets:
    - name: "docker-registry-credential"
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
